# This needs to be different from Jersey's endpoint for actuator to work
server.servlet-path: /
spring:
#    jersey.application-path: /api
    profiles.active: local
    application:
        name: Ignite.Cache.Service
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
        time-zone: UTC
        deserialization:
            adjust_dates_to_context_time_zone: false
        
            
server:
    port: 52218

# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-actuator-with-jersey
endpoints:
    enabled: false
    info:
        enabled: true
    health:
        enabled: true
    metrics:
        enabled: true

---
spring:
    profiles: local
logging:
    directory: C:/Logs

security:
    apiKeys:
        - user: test.user.api
          encryptedKey: Blahkey1
        - user: test.user.1
          encryptedKey: Blahkey2
        - user: test.user.2
          encryptedKey: WIOL96XjIig61r8WW0J5zKQhgwmFUB2VUzDMwbQhiJlfhSEAgjVShJdBjxa2/Qxg
